### ISSUE TITLE
Doubt regarding step 2

### ISSUE THREAD

**Issue by ihavenoid** [Shubham0Rajput/Rclone-Telegram-Bot#2]
Where I have to put my rclone.conf?
I am not able to get it. Sorry 

And how to add 
Drive server side copy flag in rclone.conf? 

Isn't it to be used in commands

Thx in advance and waiting for your reply 😊

**Comment by Shubham0Rajput** [comment]
open CMD in rclone folder and check do :  "rclone config file" it will give you the location for config file.

explain your 2nd problem please

**Comment by ihavenoid** [comment]
I was asking
how to put/use rclone.conf in bot?
I have that file with me
just unable to figure out, how to use it with bot

**Comment by Shubham0Rajput** [comment]
Enter "rclone config file " u will get an address to paste your rclone.conf
there.
then open that location and paste your rclone.conf you have there.
Bot will use .confg file from there.
