### ISSUE TITLE
Where i have to add bot token ?

### ISSUE THREAD

**Issue by rsoorajs** [Shubham0Rajput/Rclone-Telegram-Bot#3]
Where i have to add bot token.there is nothing saying about that in readme

**Comment by rsoorajs** [comment]
Getting this error while running the bot

![IMG_20200808_154931_767](https://user-images.githubusercontent.com/20116017/89707765-cca26680-d98e-11ea-9dd4-2380d589e7ae.jpg)

**Comment by Shubham0Rajput** [comment]
In the code where main function is. At the end of code there will be TOKEN
enter your token there

**Comment by Shubham0Rajput** [comment]
In my case, i used python 2.7 so u have to make some changes like instead of
"print path" now u have to do "print(path)".
Do same to this kind
And if any other error came to let me know.
