### ISSUE TITLE
Any way to deploy on heroku or railwayy.app?

### ISSUE THREAD

**Issue by askfriends** [Shubham0Rajput/Rclone-Telegram-Bot#4]

**Comment by Shubham0Rajput** [comment]
currently not, only on VPS

**Comment by askfriends** [comment]
> currently not, only on VPS

will u consider to add this feature?

**Comment by sridhar885** [comment]
> currently not, only on VPS

bro need proper video on installing the please what drive deteails should we add in that and why you gave autorclone repo were to clone your repo and where to add teh tg token thanks in advance

**Comment by sridhar885** [comment]
> currently not, only on VPS
and i tried to contact you n the telegram  and iseen there is no username

**Comment by sridhar885** [comment]
> currently not, only on VPS

i have faced this error with out adding 
File "bot.py", line 71
    print path
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(pat

**Comment by Shubham0Rajput** [comment]
1. replace print path with print(path)
2. Take a Raspberry Pi and deploy it as its most safe way and not much headache as I tried deploying it on Heroku it bans your account. 
3. Deploy on Pi is simple can try and if any issue let me know

**Comment by askfriends** [comment]
> 1. replace print path with print(path)
> 2. Take a Raspberry Pi and deploy it as its most safe way and not much headache as I tried deploying it on Heroku it bans your account.
> 3. Deploy on Pi is simple can try and if any issue let me know

bro there are some ways to avoid heroku ban, hav u tried deploying via github secrets?

**Comment by Shubham0Rajput** [comment]
well you can try that ;)
